### ISSUE TITLE
pgrep  -x -a -l doesn't work on some systems

### ISSUE THREAD

**Issue by BarthesSimpson** [fanout/leaderboard#2]
On some systems, `pgrep -x -a -l ssh` only gets PID and not full command, so the line `pid, cmd = line.split(' ', 1)` fails. I think `pgrep -fl ssh` works on both older and newer pgrep.

**Comment by jkarneges** [comment]
For me, `pgrep -fl ssh` doesn't show the full command, just the name of the process. Maybe we need a platform check with different commands...

**Comment by BarthesSimpson** [comment]
After a little more research, it seems like it's a Mac OS X thing. So I made this change and now the script works well on both my Mac and Linux environments:

```
def check_already_running(forwards):
    if sys.platform == 'darwin':
    ssh_args = ['pgrep', '-fl', 'ssh']
else:
    ssh_args = ['pgrep', '-x', '-a', '-l', 'ssh']
try:
    lines = subprocess.check_output(ssh_args).split('\n')
except subprocess.CalledProcessError:
    lines = list()  

for line in lines:
        # etc...
```

**Comment by jkarneges** [comment]
Cool, I've added it. Thanks!
